name: Update from git

on:
  schedule:
    - cron: '0 6 * * *'  # Executa às 3h da manhã (UTC) todos os dias
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - main
          - dev

jobs:
  deploy:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || (github.event_name == 'pull_request' && github.event.pull_request.base.ref) || 'dev' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display deployment info
        run: |
          BRANCH=$([[ "${{ github.event_name }}" == "workflow_dispatch" ]]             && echo "${{ github.event.inputs.branch }}"             || echo "${{ github.ref_name }}")
          echo "Deploying branch: $BRANCH"
          echo "Triggered by: ${{ github.event_name }}"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'

      - name: Install dependencies
        run: |
          pip install pyfabricops python-dotenv
          pip list

      - name: Run placeholders_to_parameters.py
        env:
          FAB_CLIENT_ID:        ${{ secrets.FAB_CLIENT_ID }}
          FAB_CLIENT_SECRET:    ${{ secrets.FAB_CLIENT_SECRET }}
          FAB_TENANT_ID:        ${{ secrets.FAB_TENANT_ID }}
          FAB_USERNAME:         ${{ secrets.FAB_USERNAME }}
          FAB_PASSWORD:         ${{ secrets.FAB_PASSWORD }}
          PYTHONPATH:           ${{ github.workspace }}
        run: python -m scripts.placeholders_to_parameters

      - name: Run deploy_project.py
        env:
          FAB_CLIENT_ID:        ${{ secrets.FAB_CLIENT_ID }}
          FAB_CLIENT_SECRET:    ${{ secrets.FAB_CLIENT_SECRET }}
          FAB_TENANT_ID:        ${{ secrets.FAB_TENANT_ID }}
          FAB_USERNAME:         ${{ secrets.FAB_USERNAME }}
          FAB_PASSWORD:         ${{ secrets.FAB_PASSWORD }}
          PYTHONPATH:           ${{ github.workspace }}
        run: python -m scripts.deploy_project

      - name: Run extract_parameters.py
        env:
          FAB_CLIENT_ID:        ${{ secrets.FAB_CLIENT_ID }}
          FAB_CLIENT_SECRET:    ${{ secrets.FAB_CLIENT_SECRET }}
          FAB_TENANT_ID:        ${{ secrets.FAB_TENANT_ID }}
          FAB_USERNAME:         ${{ secrets.FAB_USERNAME }}
          FAB_PASSWORD:         ${{ secrets.FAB_PASSWORD }}
          PYTHONPATH:           ${{ github.workspace }}
        run: python -m scripts.extract_parameters

      - name: Run parameters_to_placeholders.py
        env:
          FAB_CLIENT_ID:        ${{ secrets.FAB_CLIENT_ID }}
          FAB_CLIENT_SECRET:    ${{ secrets.FAB_CLIENT_SECRET }}
          FAB_TENANT_ID:        ${{ secrets.FAB_TENANT_ID }}
          FAB_USERNAME:         ${{ secrets.FAB_USERNAME }}
          FAB_PASSWORD:         ${{ secrets.FAB_PASSWORD }}
          PYTHONPATH:           ${{ github.workspace }}
        run: python -m scripts.parameters_to_placeholders

      - name: Commit changes
        run: |
          git config --local user.name  "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "chore: update from git with GitHub Actions" || echo "No changes to commit"
      
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
